# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#usuario
User.create(email: 'admin@admin.com', password: 'adminPass123', password_confirmation: 'adminPass123', role: 0, names: 'admin', last_names: 'ejemplo', identification: '000000')

# Paises
pais = Country.create!(name: 'Colombia')

# Departamentos
departamentos_data = [
  { name: 'Antioquia', country_id: pais.id },
  { name: 'Atlantico', country_id: pais.id },
  { name: 'Bolivar', country_id: pais.id },
  { name: 'Boyaca', country_id: pais.id },
  { name: 'Caldas', country_id: pais.id },
  { name: 'Cauca', country_id: pais.id },
  { name: 'Cesar', country_id: pais.id },
  { name: 'Cordoba', country_id: pais.id },
  { name: 'Cundinamarca', country_id: pais.id },
  { name: 'Guajira', country_id: pais.id },
  { name: 'Huila', country_id: pais.id },
  { name: 'Magdalena', country_id: pais.id },
  { name: 'Meta', country_id: pais.id },
  { name: 'Nariño', country_id: pais.id },
  { name: 'Norte de Santander', country_id: pais.id },
  { name: 'Quindio', country_id: pais.id },
  { name: 'Risaralda', country_id: pais.id },
  { name: 'Santander', country_id: pais.id },
  { name: 'Sucre', country_id: pais.id },
  { name: 'Tolima', country_id: pais.id },
  { name: 'Valle del Cauca', country_id: pais.id }
]

Department.create!(departamentos_data)

# Ciudades
ciudades_data = [
  { name: 'Bello', department_id: 1 },
  { name: 'Caldas', department_id: 1 },
  { name: 'Copacabana', department_id: 1 },
  { name: 'Envigado', department_id: 1 },
  { name: 'Guarne', department_id: 1 },
  { name: 'Itagui', department_id: 1 },
  { name: 'La Ceja', department_id: 1 },
  { name: 'La Estrella', department_id: 1 },
  { name: 'La Tablaza', department_id: 1 },
  { name: 'Marinilla', department_id: 1 },
  { name: 'Medellin', department_id: 1 },
  { name: 'Rionegro', department_id: 1 },
  { name: 'Sabaneta', department_id: 1 },
  { name: 'San Antonio de Prado', department_id: 1 },
  { name: 'San Cristobal', department_id: 1 },
  { name: 'Caucasia', department_id: 1 },
  { name: 'Barranquilla', department_id: 2 },
  { name: 'Malambo', department_id: 2 },
  { name: 'Puerto Colombia', department_id: 2 },
  { name: 'Soledad', department_id: 2 },
  { name: 'Arjona', department_id: 3 },
  { name: 'Bayunca', department_id: 3 },
  { name: 'Carmen de Bolivar', department_id: 3 },
  { name: 'Cartagena', department_id: 3 },
  { name: 'Turbaco', department_id: 3 },
  { name: 'Arcabuco', department_id: 4 },
  { name: 'Belencito', department_id: 4 },
  { name: 'Chiquinquira', department_id: 4 },
  { name: 'Combita', department_id: 4 },
  { name: 'Cucaita', department_id: 4 },
  { name: 'Duitama', department_id: 4 },
  { name: 'Mongui', department_id: 4 },
  { name: 'Nobsa', department_id: 4 },
  { name: 'Paipa', department_id: 4 },
  { name: 'Puerto Boyaca', department_id: 4 },
  { name: 'Raquira', department_id: 4 },
  { name: 'Samaca', department_id: 4 },
  { name: 'Santa Rosa de Viterbo', department_id: 4 },
  { name: 'Sogamoso', department_id: 4 },
  { name: 'Sutamerchan', department_id: 4 },
  { name: 'Tibasosa', department_id: 4 },
  { name: 'Tinjaca', department_id: 4 },
  { name: 'Tunja', department_id: 4 },
  { name: 'Ventaquemada', department_id: 4 },
  { name: 'Villa de Leiva', department_id: 4 },
  { name: 'La Dorada', department_id: 5 },
  { name: 'Manizales', department_id: 5 },
  { name: 'Villamaria', department_id: 5 },
  { name: 'Caloto', department_id: 6 },
  { name: 'Ortigal', department_id: 6 },
  { name: 'Piendamo', department_id: 6 },
  { name: 'Popayan', department_id: 6 },
  { name: 'Puerto Tejada', department_id: 6 },
  { name: 'Santander Quilichao', department_id: 6 },
  { name: 'Tunia', department_id: 6 },
  { name: 'Villarica', department_id: 6 },
  { name: 'Valledupar', department_id: 7 },
  { name: 'Cerete', department_id: 8 },
  { name: 'Monteria', department_id: 8 },
  { name: 'Planeta Rica', department_id: 8 },
  { name: 'Alban', department_id: 9 },
  { name: 'Bogota', department_id: 9 },
  { name: 'Bojaca', department_id: 9 },
  { name: 'Bosa', department_id: 9 },
  { name: 'Briceño', department_id: 9 },
  { name: 'Cajica', department_id: 9 },
  { name: 'Chia', department_id: 9 },
  { name: 'Chinauta', department_id: 9 },
  { name: 'Choconta', department_id: 9 },
  { name: 'Cota', department_id: 9 },
  { name: 'El Muña', department_id: 9 },
  { name: 'El Rosal', department_id: 9 },
  { name: 'Engativa', department_id: 9 },
  { name: 'Facatativa', department_id: 9 },
  { name: 'Fontibon', department_id: 9 },
  { name: 'Funza', department_id: 9 },
  { name: 'Fusagasuga', department_id: 9 },
  { name: 'Gachancipa', department_id: 9 },
  { name: 'Girardot', department_id: 9 },
  { name: 'Guaduas', department_id: 9 },
  { name: 'Guayavetal', department_id: 9 },
  { name: 'La Calera', department_id: 9 },
  { name: 'La Caro', department_id: 9 },
  { name: 'Madrid', department_id: 9 },
  { name: 'Mosquera', department_id: 9 },
  { name: 'Nemocon', department_id: 9 },
  { name: 'Puente Piedra', department_id: 9 },
  { name: 'Puente Quetame', department_id: 9 },
  { name: 'Puerto Bogota', department_id: 9 },
  { name: 'Puerto Salgar', department_id: 9 },
  { name: 'Quetame', department_id: 9 },
  { name: 'Sasaima', department_id: 9 },
  { name: 'Sesquile', department_id: 9 },
  { name: 'Sibate', department_id: 9 },
  { name: 'Silvania', department_id: 9 },
  { name: 'Simijaca', department_id: 9 },
  { name: 'Soacha', department_id: 9 },
  { name: 'Sopo', department_id: 9 },
  { name: 'Suba', department_id: 9 },
  { name: 'Subachoque', department_id: 9 },
  { name: 'Susa', department_id: 9 },
  { name: 'Tabio', department_id: 9 },
  { name: 'Tenjo', department_id: 9 },
  { name: 'Tocancipa', department_id: 9 },
  { name: 'Ubate', department_id: 9 },
  { name: 'Usaquen', department_id: 9 },
  { name: 'Usme', department_id: 9 },
  { name: 'Villapinzon', department_id: 9 },
  { name: 'Villeta', department_id: 9 },
  { name: 'Zipaquira', department_id: 9 },
  { name: 'Maicao', department_id: 10 },
  { name: 'Riohacha', department_id: 10 },
  { name: 'Aipe', department_id: 11 },
  { name: 'Neiva', department_id: 11 },
  { name: 'Cienaga', department_id: 12 },
  { name: 'Gaira', department_id: 12 },
  { name: 'Rodadero', department_id: 12 },
  { name: 'Santa Marta', department_id: 12 },
  { name: 'Taganga', department_id: 12 },
  { name: 'Villavicencio', department_id: 13 },
  { name: 'Ipiales', department_id: 14 },
  { name: 'Pasto', department_id: 14 },
  { name: 'Cucuta', department_id: 15 },
  { name: 'El Zulia', department_id: 15 },
  { name: 'La Parada', department_id: 15 },
  { name: 'Los Patios', department_id: 15 },
  { name: 'Villa del Rosario', department_id: 15 },
  { name: 'Armenia', department_id: 16 },
  { name: 'Calarca', department_id: 16 },
  { name: 'Circasia', department_id: 16 },
  { name: 'La Tebaida', department_id: 16 },
  { name: 'Montenegro', department_id: 16 },
  { name: 'Quimbaya', department_id: 16 },
  { name: 'Dosquebradas', department_id: 17 },
  { name: 'Pereira', department_id: 17 },
  { name: 'Aratoca', department_id: 18 },
  { name: 'Barbosa', department_id: 18 },
  { name: 'Bucaramanga', department_id: 18 },
  { name: 'Floridablanca', department_id: 18 },
  { name: 'Giron', department_id: 18 },
  { name: 'Lebrija', department_id: 18 },
  { name: 'Oiba', department_id: 18 },
  { name: 'Piedecuesta', department_id: 18 },
  { name: 'Pinchote', department_id: 18 },
  { name: 'San Gil', department_id: 18 },
  { name: 'Socorro', department_id: 18 },
  { name: 'Sincelejo', department_id: 19 },
  { name: 'Armero', department_id: 20 },
  { name: 'Buenos Aires', department_id: 20 },
  { name: 'Castilla', department_id: 20 },
  { name: 'Espinal', department_id: 20 },
  { name: 'Flandes', department_id: 20 },
  { name: 'Guamo', department_id: 20 },
  { name: 'Honda', department_id: 20 },
  { name: 'Ibague', department_id: 20 },
  { name: 'Mariquita', department_id: 20 },
  { name: 'Melgar', department_id: 20 },
  { name: 'Natagaima', department_id: 20 },
  { name: 'Payande', department_id: 20 },
  { name: 'Purificacion', department_id: 20 },
  { name: 'Saldaña', department_id: 20 },
  { name: 'Tolemaida', department_id: 20 },
  { name: 'Amaime', department_id: 21 },
  { name: 'Andalucia', department_id: 21 },
  { name: 'Buenaventura', department_id: 21 },
  { name: 'Buga', department_id: 21 },
  { name: 'Buga La Grande', department_id: 21 },
  { name: 'Caicedonia', department_id: 21 },
  { name: 'Cali', department_id: 21 },
  { name: 'Candelaria', department_id: 21 },
  { name: 'Cartago', department_id: 21 },
  { name: 'Cavasa', department_id: 21 },
  { name: 'Costa Rica', department_id: 21 },
  { name: 'Dagua', department_id: 21 },
  { name: 'El Carmelo', department_id: 21 },
  { name: 'El Cerrito', department_id: 21 },
  { name: 'El Placer', department_id: 21 },
  { name: 'Florida', department_id: 21 },
  { name: 'Ginebra', department_id: 21 },
  { name: 'Guacari', department_id: 21 },
  { name: 'Jamundi', department_id: 21 },
  { name: 'La Paila', department_id: 21 },
  { name: 'La Union', department_id: 21 },
  { name: 'La Victoria', department_id: 21 },
  { name: 'Loboguerrero', department_id: 21 },
  { name: 'Palmira', department_id: 21 },
  { name: 'Pradera', department_id: 21 },
  { name: 'Roldanillo', department_id: 21 },
  { name: 'Rozo', department_id: 21 },
  { name: 'San Pedro', department_id: 21 },
  { name: 'Sevilla', department_id: 21 },
  { name: 'Sonso', department_id: 21 },
  { name: 'Tulua', department_id: 21 },
  { name: 'Vijes', department_id: 21 },
  { name: 'Villa Gorgona', department_id: 21 },
  { name: 'Yotoco', department_id: 21 },
  { name: 'Yumbo', department_id: 21 },
  { name: 'Zarzal', department_id: 21 }
]

City.create!(ciudades_data)